### ISSUE TITLE
empty utm_source creates type error

### ISSUE THREAD

**Issue by m-lotze** [spatie/laravel-referer#17]
If utm_source is empty (http://test.de/?utm_source) the method getReferer in UtmSource creates a type error:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of Spatie\Referer\Sources\UtmSource::getReferer() must be of the type string, null returned
```

I think this is because Laravel converts empty strings to null by default.

**Comment by sebastiandedeyne** [comment]
Thanks for reporting! Should be fixed in `v1.3.2` :)
