### ISSUE TITLE
Error encountered when running following command: php artisan vendor:publish --provider="Spatie\Referer\RefererServiceProvider"

### ISSUE THREAD

**Issue by saularis** [spatie/laravel-referer#29]
After running the following command I encountered the following error.
**Command:** `php artisan vendor:publish --provider="Spatie\Referer\RefererServiceProvider"`
**ERROR:**
```
Uncaught Error: Call to undefined function Symfony\Component\Debug\Exception\get_debug_type() in C:\\...\....\....\....\vendor\symfony\debug\Exception\FatalThrowableError.php:29                                        
```
spatie/laravel-referer version: 1.3.3
Laravel version: 5.7
PHP version: 7.3
Laravel spark version: 7

Let me know if you need more information, Thanks

**Comment by octoper** [comment]
I think that error occurs because the min Laravel version for this package is 5.8.0
