### ISSUE TITLE
Not working on Lumen

### ISSUE THREAD

**Issue by alignwebs** [spatie/laravel-referer#32]
I tried installing it on lumen 7.0

It gives the following error
`Call to undefined function Spatie\Referer\config_path() (500 Internal Server Error)`
![image](https://user-images.githubusercontent.com/7644807/88660200-eb357180-d0f3-11ea-9858-1b2988eedd90.png)

Is there a fix for it ?

**Comment by freekmurze** [comment]
We don't support lumen. Feel free to fork and adapt to your needs
