### ISSUE TITLE
Can't locate path: ...referer.php

### ISSUE THREAD

**Issue by trixanapp** [spatie/laravel-referer#9]
You can publish the config file with:
php artisan vendor:publish --provider="Spatie\Referer\RefererServiceProvider"
Error:
Can't locate path: </home/vagrant/code/homestead/vendor/spatie/laravel-referer/src/../resources/config/referer.php>
And:
Class 'App\Spatie\Referer\Referer' not found
And:
use Referer;
Class 'Referer' not found

In Laravel 5.4 with php 7.1

**Comment by freekmurze** [comment]
A tagged a new release that fixes this. Run composer update to pull in `v1.2.1`
